"""add_sanpo_maps_and_pins

Revision ID: 3584d0dc1bb8
Revises: ecd8f161fedb
Create Date: 2026-09-21 06:56:29.462067

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3584d0dc1bb8'
down_revision: str | None = 'ecd8f161fedb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pin_photo_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('declared_byte_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'attached')", name='ck_pin_photo_uploads_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pin_photo_uploads_user_id_status_expires_at', 'pin_photo_uploads', ['user_id', 'status', 'expires_at'], unique=False)
    op.create_table('sanpo_maps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sanpo_maps_owner_user_id', 'sanpo_maps', ['owner_user_id'], unique=False)
    op.create_index('uq_sanpo_maps_owner_user_id_is_default', 'sanpo_maps', ['owner_user_id'], unique=True, postgresql_where=sa.text('is_default'))
    op.create_table('pins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sanpo_map_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('client_pin_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('client_walk_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sanpo_map_id'], ['sanpo_maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by_user_id', 'client_pin_id', name='uq_pins_created_by_user_id_client_pin_id')
    )
    op.create_index('ix_pins_sanpo_map_id_created_at_id', 'pins', ['sanpo_map_id', 'created_at', 'id'], unique=False)
    op.create_table('sanpo_map_members',
    sa.Column('sanpo_map_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'editor')", name='ck_sanpo_map_members_role'),
    sa.ForeignKeyConstraint(['sanpo_map_id'], ['sanpo_maps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sanpo_map_id', 'user_id', name='pk_sanpo_map_members')
    )
    op.create_index('ix_sanpo_map_members_user_id', 'sanpo_map_members', ['user_id'], unique=False)
    op.create_table('pin_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pin_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('thumbnail_s3_key', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_byte_size', sa.Integer(), nullable=True),
    sa.Column('thumbnail_width', sa.Integer(), nullable=True),
    sa.Column('thumbnail_height', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pin_id'], ['pins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key', name='uq_pin_photos_s3_key'),
    sa.UniqueConstraint('upload_id', name='uq_pin_photos_upload_id')
    )
    op.create_index('ix_pin_photos_pin_id_position', 'pin_photos', ['pin_id', 'position'], unique=False)
    op.create_index('ix_pin_photos_uploaded_by_user_id', 'pin_photos', ['uploaded_by_user_id'], unique=False)
    op.create_table('pin_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pin_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('label_key', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pin_id'], ['pins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pin_id', 'label_key', name='uq_pin_tags_pin_id_label_key')
    )
    op.create_index('ix_pin_tags_created_by_user_id', 'pin_tags', ['created_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pin_tags_created_by_user_id', table_name='pin_tags')
    op.drop_table('pin_tags')
    op.drop_index('ix_pin_photos_uploaded_by_user_id', table_name='pin_photos')
    op.drop_index('ix_pin_photos_pin_id_position', table_name='pin_photos')
    op.drop_table('pin_photos')
    op.drop_index('ix_sanpo_map_members_user_id', table_name='sanpo_map_members')
    op.drop_table('sanpo_map_members')
    op.drop_index('ix_pins_sanpo_map_id_created_at_id', table_name='pins')
    op.drop_table('pins')
    op.drop_index('uq_sanpo_maps_owner_user_id_is_default', table_name='sanpo_maps', postgresql_where=sa.text('is_default'))
    op.drop_index('ix_sanpo_maps_owner_user_id', table_name='sanpo_maps')
    op.drop_table('sanpo_maps')
    op.drop_index('ix_pin_photo_uploads_user_id_status_expires_at', table_name='pin_photo_uploads')
    op.drop_table('pin_photo_uploads')
    # ### end Alembic commands ###
